### ISSUE TITLE
Apt failure to fetch seamonkey-mozilla-build_2.53.9.1-0ubuntu1 - Certificate verification failed

### ISSUE THREAD

**Issue by DesktopECHO** [nanotube/ubuntuzilla#2]
`Err:5 https://iweb.dl.sourceforge.net/project/ubuntuzilla/mozilla/apt all Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 192.175.120.182 443]`

Everything was fine yesterday, anyone else seeing this?

**Comment by nanotube** [comment]
looks like an issue with one of the sourceforge mirrors... i'd try again until the mirror rotation gives you a different server.
